backend/api/battles/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.BattleListCreateEndpoint.as_view(), name="battle_list_create"),
    path("<int:pk>", views.BattleRetrieveUpdateEndpoint.as_view(), name="battle_retrieve_update"),
]

backend/battles/urls.py
from django.urls import path

from . import views

app_name = "battles"

urlpatterns = [
    path("", views.BattleList.as_view(), name="battle_list"),
    path("add", views.BattleCreate.as_view(), name="battle_create"),
    path("<int:pk>", views.BattleDetail.as_view(), name="battle_detail"),
    path(
        "<int:pk>/opponent-pokemons",
        views.BattleUpdateOpponentPokemons.as_view(),
        name="battle_update_opponent_pokemons",
    ),
    path("settled", views.SettledBattlesList.as_view(), name="settled_battles_list"),
    path("ongoing", views.OngoingBattlesList.as_view(), name="ongoing_battles_list"),
]

backend/users/urls.py
from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path("signup", views.SignUp.as_view(), name="user_signup"),
    path("login", views.Login.as_view(), name="user_login"),
    path("logout", views.Logout.as_view(), name="user_logout"),
]

backend/battles/models.py
from django.db import models
from django.urls import reverse

from battles.helpers import get_battle_result
from pokemons.models import Pokemon
from users.models import User


class BattleQuerySet(models.QuerySet):
    def settled(self):
        return self.filter(
            opponent_pokemon_1__isnull=False,
            opponent_pokemon_2__isnull=False,
            opponent_pokemon_3__isnull=False,
        )

    def ongoing(self):
        return self.filter(
            opponent_pokemon_1__isnull=True,
            opponent_pokemon_2__isnull=True,
            opponent_pokemon_3__isnull=True,
        )


class Battle(models.Model):
    creator = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="battle_as_creator",
    )
    opponent = models.ForeignKey(User, on_delete=models.CASCADE, related_name="battle_as_opponent")
    created_at = models.DateTimeField(auto_now_add=True, null=True)

    creator_pokemon_1 = models.ForeignKey(
        Pokemon,
        on_delete=models.CASCADE,
        related_name="battle_as_creator_pokemon_1",
        blank=True,
        null=True,
    )
    creator_pokemon_2 = models.ForeignKey(
        Pokemon,
        on_delete=models.CASCADE,
        related_name="battle_as_creator_pokemon_2",
        blank=True,
        null=True,
    )
    creator_pokemon_3 = models.ForeignKey(
        Pokemon,
        on_delete=models.CASCADE,
        related_name="battle_as_creator_pokemon_3",
        blank=True,
        null=True,
    )

    opponent_pokemon_1 = models.ForeignKey(
        Pokemon,
        on_delete=models.CASCADE,
        related_name="battle_as_opponent_pokemon_1",
        blank=True,
        null=True,
    )
    opponent_pokemon_2 = models.ForeignKey(
        Pokemon,
        on_delete=models.CASCADE,
        related_name="battle_as_opponent_pokemon_2",
        blank=True,
        null=True,
    )
    opponent_pokemon_3 = models.ForeignKey(
        Pokemon,
        on_delete=models.CASCADE,
        related_name="battle_as_opponent_pokemon_3",
        blank=True,
        null=True,
    )

    objects = BattleQuerySet().as_manager()

    @property
    def winner(self):
        return get_battle_result(self)

    def has_been_resolved(self):
        return all(
            [
                self.creator_pokemon_1,
                self.creator_pokemon_2,
                self.creator_pokemon_3,
                self.opponent_pokemon_1,
                self.opponent_pokemon_2,
                self.opponent_pokemon_3,
            ]
        )

    def __str__(self):
        return f"Battle #{self.id}: {self.creator.email} X {self.opponent.email}"

    def get_absolute_url(self):
        return reverse("battles:battle_detail", kwargs={"pk": self.pk})

backend/battles/forms.py
from dal import autocomplete

from django import forms

from battles.exceptions import DuplicatedPokemonPositions
from battles.helpers import position_pokemons
from battles.models import Battle
from pokemons.exceptions import PokemonNotFound
from pokemons.helpers import get_pokemons_points_sum
from pokemons.models import Pokemon
from pokemons.services import pokemon_exists
from users.models import User

POKEMON_POSITION_CHOICES = [
    (1, "Position 1"),
    (2, "Position 2"),
    (3, "Position 3"),
]


class BattleForm(forms.ModelForm):
    creator = forms.ModelChoiceField(required=False, queryset=User.objects.all())

    creator_pokemon_1 = forms.ModelChoiceField(
        queryset=Pokemon.objects.all(),
        widget=autocomplete.ModelSelect2(url="pokemons:pokemon_autocomplete"),
    )
    creator_pokemon_2 = forms.ModelChoiceField(
        queryset=Pokemon.objects.all(),
        widget=autocomplete.ModelSelect2(url="pokemons:pokemon_autocomplete"),
    )
    creator_pokemon_3 = forms.ModelChoiceField(
        queryset=Pokemon.objects.all(),
        widget=autocomplete.ModelSelect2(url="pokemons:pokemon_autocomplete"),
    )

    position_creator_pokemon_1 = forms.ChoiceField(
        choices=POKEMON_POSITION_CHOICES, initial=1, required=False
    )
    position_creator_pokemon_2 = forms.ChoiceField(
        choices=POKEMON_POSITION_CHOICES, initial=2, required=False
    )
    position_creator_pokemon_3 = forms.ChoiceField(
        choices=POKEMON_POSITION_CHOICES, initial=3, required=False
    )

    class Meta:
        model = Battle
        fields = [
            "creator",
            "opponent",
            "creator_pokemon_1",
            "creator_pokemon_2",
            "creator_pokemon_3",
            "position_creator_pokemon_1",
            "position_creator_pokemon_2",
            "position_creator_pokemon_3",
        ]

    def __init__(self, *args, **kwargs):
        self.current_user = kwargs.pop("current_user")
        super(BattleForm, self).__init__(*args, **kwargs)
        self.fields["opponent"].queryset = User.objects.exclude(email=self.current_user.email)
        self.fields["creator"].initial = self.current_user

    def clean_creator_pokemon_1(self):
        data = self.cleaned_data.get("creator_pokemon_1")
        if not pokemon_exists(data):
            self.add_error("creator_pokemon_1", "Sorry, this pokemon was not found")
        return data

    def clean_creator_pokemon_2(self):
        data = self.cleaned_data.get("creator_pokemon_2")
        if not pokemon_exists(data):
            self.add_error("creator_pokemon_2", "Sorry, this pokemon was not found")
        return data

    def clean_creator_pokemon_3(self):
        data = self.cleaned_data.get("creator_pokemon_3")
        if not pokemon_exists(data):
            self.add_error("creator_pokemon_3", "Sorry, this pokemon was not found")
        return data

    def clean(self):
        cleaned_data = super().clean()
        cleaned_data["creator"] = self.fields["creator"].initial

        creator_pokemon_1 = cleaned_data.get("creator_pokemon_1")
        creator_pokemon_2 = cleaned_data.get("creator_pokemon_2")
        creator_pokemon_3 = cleaned_data.get("creator_pokemon_3")

        position_creator_pokemon_1 = cleaned_data.get("position_creator_pokemon_1")
        position_creator_pokemon_2 = cleaned_data.get("position_creator_pokemon_2")
        position_creator_pokemon_3 = cleaned_data.get("position_creator_pokemon_3")

        pokemon_points_sum = 0
        try:
            pokemon_points_sum = get_pokemons_points_sum(
                [creator_pokemon_1.name, creator_pokemon_2.name, creator_pokemon_3.name]
            )
        except PokemonNotFound:
            pass

        if pokemon_points_sum > 600:
            raise forms.ValidationError("Pokemons' points sum cannot be more than 600")

        # The exception treatment needs to be in clean method,
        # so it can show the Validation Error in the form
        try:
            position_pokemons(
                [creator_pokemon_1, creator_pokemon_2, creator_pokemon_3],
                [
                    position_creator_pokemon_1,
                    position_creator_pokemon_2,
                    position_creator_pokemon_3,
                ],
            )
        except DuplicatedPokemonPositions:
            raise forms.ValidationError("Please add each Pokemon in a different position")

        return cleaned_data

    def save(self, commit=True):
        creator_pokemon_1 = self.cleaned_data.get("creator_pokemon_1")
        creator_pokemon_2 = self.cleaned_data.get("creator_pokemon_2")
        creator_pokemon_3 = self.cleaned_data.get("creator_pokemon_3")

        position_creator_pokemon_1 = self.cleaned_data.get("position_creator_pokemon_1")
        position_creator_pokemon_2 = self.cleaned_data.get("position_creator_pokemon_2")
        position_creator_pokemon_3 = self.cleaned_data.get("position_creator_pokemon_3")

        positioned_pokemons = position_pokemons(
            [creator_pokemon_1, creator_pokemon_2, creator_pokemon_3],
            [position_creator_pokemon_1, position_creator_pokemon_2, position_creator_pokemon_3],
        )

        self.instance.creator_pokemon_1 = positioned_pokemons[0]
        self.instance.creator_pokemon_2 = positioned_pokemons[1]
        self.instance.creator_pokemon_3 = positioned_pokemons[2]

        return super(BattleForm, self).save(commit)


class BattleOpponentPokemonsForm(forms.ModelForm):
    opponent_pokemon_1 = forms.ModelChoiceField(
        queryset=Pokemon.objects.all(),
        widget=autocomplete.ModelSelect2(url="pokemons:pokemon_autocomplete"),
    )
    opponent_pokemon_2 = forms.ModelChoiceField(
        queryset=Pokemon.objects.all(),
        widget=autocomplete.ModelSelect2(url="pokemons:pokemon_autocomplete"),
    )
    opponent_pokemon_3 = forms.ModelChoiceField(
        queryset=Pokemon.objects.all(),
        widget=autocomplete.ModelSelect2(url="pokemons:pokemon_autocomplete"),
    )

    class Meta:
        model = Battle
        fields = [
            "opponent_pokemon_1",
            "opponent_pokemon_2",
            "opponent_pokemon_3",
        ]

    def clean_opponent_pokemon_1(self):
        data = self.cleaned_data.get("opponent_pokemon_1")
        if not pokemon_exists(data):
            self.add_error("opponent_pokemon_1", "Sorry, this pokemon was not found")
        return data

    def clean_opponent_pokemon_2(self):
        data = self.cleaned_data.get("opponent_pokemon_2")
        if not pokemon_exists(data):
            self.add_error("opponent_pokemon_2", "Sorry, this pokemon was not found")
        return data

    def clean_opponent_pokemon_3(self):
        data = self.cleaned_data.get("opponent_pokemon_3")
        if not pokemon_exists(data):
            self.add_error("opponent_pokemon_3", "Sorry, this pokemon was not found")
        return data

    def clean(self):
        cleaned_data = super().clean()

        opponent_pokemon_1 = cleaned_data.get("opponent_pokemon_1")
        opponent_pokemon_2 = cleaned_data.get("opponent_pokemon_2")
        opponent_pokemon_3 = cleaned_data.get("opponent_pokemon_3")

        pokemon_points_sum = 0
        try:
            pokemon_points_sum = get_pokemons_points_sum(
                [opponent_pokemon_1.name, opponent_pokemon_2.name, opponent_pokemon_3.name]
            )
        except PokemonNotFound:
            pass

        if pokemon_points_sum > 600:
            raise forms.ValidationError("Pokemons' points sum cannot be more than 600")

        return cleaned_data

backend/api/battles/views.py
from django.shortcuts import render, redirect  # noqa
from rest_framework import generics
from rest_framework.permissions import IsAuthenticated

from api.battles.serializers import BattleSerializer
from battles.models import Battle


class BattleListCreateEndpoint(generics.ListCreateAPIView):
    serializer_class = BattleSerializer
    queryset = Battle.objects.all()
    permission_classes = (IsAuthenticated,)


class BattleRetrieveUpdateEndpoint(generics.RetrieveUpdateAPIView):
    serializer_class = BattleSerializer
    queryset = Battle.objects.all()
    permission_classes = (IsAuthenticated,)

backend/battles/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, DetailView, ListView, UpdateView

from battles.forms import BattleForm, BattleOpponentPokemonsForm
from battles.helpers import send_battle_result
from battles.models import Battle


class BattleCreate(LoginRequiredMixin, CreateView):
    template_name = "battles/battle_form.html"
    form_class = BattleForm
    login_url = reverse_lazy("users:user_login")

    def get_form_kwargs(self):
        kwargs = super(BattleCreate, self).get_form_kwargs()
        kwargs["current_user"] = self.request.user
        return kwargs

    def get_success_url(self):
        return reverse("battles:battle_update_opponent_pokemons", kwargs={"pk": self.object.pk})


class BattleUpdateOpponentPokemons(LoginRequiredMixin, UpdateView):
    model = Battle
    form_class = BattleOpponentPokemonsForm
    template_name = "battles/battle_opponent_pokemons_form.html"
    login_url = reverse_lazy("users:user_login")

    def post(self, request, *args, **kwargs):
        super(BattleUpdateOpponentPokemons, self).post(request, *args, **kwargs)
        send_battle_result(self.get_object())
        return redirect(self.get_success_url())


class BattleDetail(LoginRequiredMixin, DetailView):
    model = Battle
    login_url = reverse_lazy("users:user_login")


class BattleList(LoginRequiredMixin, ListView):
    model = Battle
    login_url = reverse_lazy("users:user_login")


class SettledBattlesList(LoginRequiredMixin, ListView):
    model = Battle
    template_name = "battles/battle_settled_list.html"
    login_url = reverse_lazy("users:user_login")

    def get_queryset(self):
        return Battle.objects.settled()


class OngoingBattlesList(LoginRequiredMixin, ListView):
    model = Battle
    template_name = "battles/battle_ongoing_list.html"
    login_url = reverse_lazy("users:user_login")

    def get_queryset(self):
        return Battle.objects.ongoing()

backend/battles/templates/battles/battle_detail.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'css/global.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/battle_styles.css' %}" />

<h1>Pokebattle #{{ object.id }}</h1>
<p id="battle-creator"><strong>Creator:</strong> {{ object.creator }}</p>
<p id="battle-opponent"><strong>Opponent:</strong> {{ object.opponent }}</p>

<div id="battle-teams">
  <div class="battle-team">
    <h2 class="heading-team">Creator's Team</h2>
    <div class="pokemon">
      <p><strong>Pokemon 1:</strong> {{ object.creator_pokemon_1.name }}</p>
      <img src="{{ object.creator_pokemon_1.image.name }}" />
    </div>
    <div class="pokemon">
      <p><strong>Pokemon 2:</strong> {{ object.creator_pokemon_2.name  }}</p>
      <img src="{{ object.creator_pokemon_2.image.name }}" />
    </div>
    <div class="pokemon">
      <p><strong>Pokemon 3:</strong> {{ object.creator_pokemon_3.name  }}</p>
      <img src="{{ object.creator_pokemon_3.image.name }}" />
    </div>
  </div>

  <div class="battle-team">
    <h2 class="heading-team">Opponent's Team</h2>
    {% if not object.has_been_resolved %}
      <p>Not added yet.</p>
    {% else %}
      <div class="pokemon">
        <p><strong>Pokemon 1:</strong> {{ object.opponent_pokemon_1.name  }}</p>
        <img src="{{ object.opponent_pokemon_1.image.name }}" />
      </div>
      <div class="pokemon">
        <p><strong>Pokemon 2:</strong> {{ object.opponent_pokemon_2.name  }}</p>
        <img src="{{ object.opponent_pokemon_2.image.name }}" />
      </div>
      <div>
        <p><strong>Pokemon 3:</strong> {{ object.opponent_pokemon_3.name  }}</p>
        <img src="{{ object.opponent_pokemon_3.image.name }}" />
      </div>
    {% endif %}
  </div>
</div>
{% if object.has_been_resolved %}
  <h2 class="heading-team">Result</h2>
  <p><strong>Winner:</strong> {{ object.winner.email }}</p>
{% endif %}

<a class="nav-link" href="{% url 'battles:battle_list' %}">Back to list</a>

backend/battles/templates/battles/battle_form.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'css/global.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/battle_styles.css' %}" />

<h1>Create a new Pokebattle</h1>
<form id="battle-form" action="{% url 'battles:battle_create' %}" method="post">
    {% csrf_token %}
  <span class="field-error">{{ form.non_field_errors }}</span>
  <div class="field-wrapper">
    <label for="{{ form.opponent.id_for_label }}">Opponent:</label>
    {{ form.opponent }}
    <span class="field-error">{{ form.opponent.errors }}</span>
  </div>
  <div class="field-wrapper">
    <label for="{{ form.creator_pokemon_1.id_for_label }}">Pokemon 1:</label>
    {{ form.creator_pokemon_1 }}
    <span class="field-error">{{ form.creator_pokemon_1.errors }}</span>
  </div>
  <div class="field-wrapper">
    <label for="{{ form.creator_pokemon_2.id_for_label }}">Pokemon 2:</label>
    {{ form.creator_pokemon_2 }}
    <span class="field-error">{{ form.creator_pokemon_2.errors }}</span>
  </div>
  <div class="field-wrapper">
    <label for="{{ form.creator_pokemon_3.id_for_label }}">Pokemon 3:</label>
    {{ form.creator_pokemon_3 }}
    <span class="field-error">{{ form.creator_pokemon_3.errors }}</span>
  </div>
  <div class="field-wrapper">
    <label for="{{ form.position_creator_pokemon_1.id_for_label }}">Pokemon 1 position:</label>
    {{ form.position_creator_pokemon_1 }}
    <span class="field-error">{{ form.position_creator_pokemon_1.errors }}</span>
  </div>
  <div class="field-wrapper">
    <label for="{{ form.position_creator_pokemon_2.id_for_label }}">Pokemon 2 position:</label>
    {{ form.position_creator_pokemon_2 }}
    <span class="field-error">{{ form.position_creator_pokemon_2.errors }}</span>
  </div>
  <div class="field-wrapper">
    <label for="{{ form.position_creator_pokemon_3.id_for_label }}">Pokemon 3 position:</label>
    {{ form.position_creator_pokemon_3 }}
    <span class="field-error">{{ form.position_creator_pokemon_3.errors }}</span>
  </div>
  <button type="submit">Create Battle</button>
</form>
<a class="nav-link" href="{% url 'battles:battle_list' %}">Back to list</a>

<!--
django-autocomplete-light configurations to use autocompletes outside the admin
https://django-autocomplete-light.readthedocs.io/en/master/tutorial.html#using-autocompletes-outside-the-admin
-->
<script type="text/javascript" src="{% static 'admin/js/vendor/jquery/jquery.js' %}"></script>

{{ form.media }}
<script>
  (function($) {
      $('#add-form').click(function() {
          var index = $('#id_inline_test_models-TOTAL_FORMS').val()
          var newTable = $('#id_inline_test_models-__prefix__-DELETE').parents('table').clone()
          newTable.find(':input').each(function() {
              for (attr of ['name', 'id'])
                  $(this).attr(
                      attr,
                      $(this).attr(attr).replace('__prefix__', index)
                  )
          })
          newTable.insertBefore($(this))
          $('#id_inline_test_models-TOTAL_FORMS').val(
              parseInt($('#id_inline_test_models-TOTAL_FORMS').val()) + 1
          )
          newTable.slideDown()
      })
  })($)
  </script>

backend/battles/templates/battles/battle_list.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'css/global.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/battle_styles.css' %}" />

<header class="header">
  <h1>Battles</h1>
  <div class="user-info">
    <span>{{ user.email }}</span>
    <a href="{% url 'users:user_logout' %}">Log out</a>
  </div>
</header>
<nav class="navigation">
  <a class="nav-link" href="{% url 'battles:battle_create' %}">Add new</a>
  <a class="nav-link" href="{% url 'battles:settled_battles_list' %}">Settled</a>
  <a class="nav-link" href="{% url 'battles:ongoing_battles_list' %}">Ongoing</a>
</nav>
<ul id="battles-list">
  {% for battle in object_list %}
  <li><a href="{% url 'battles:battle_detail' battle.id %}">Pokebattle {{ battle.id }}</a></li>
  {% empty %}
    <li>No battles yet.</li>
  {% endfor %}
</ul>

backend/battles/templates/battles/battle_ongoing_list.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'css/global.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/battle_styles.css' %}" />

<h1>Battles</h1>
<ul id="battles-list">
  {% for battle in object_list %}
  <li><a href="{% url 'battles:battle_detail' battle.id %}">Pokebattle {{ battle.id }}</a></li>
  {% empty %}
    <li>No battles yet.</li>
  {% endfor %}
</ul>
<a class="nav-link" href="{% url 'battles:battle_list' %}">Back to all battles</a>

backend/battles/templates/battles/battle_opponent_pokemons_form.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'css/global.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/battle_styles.css' %}" />

<h1>Hey, {{ object.opponent.email }}!</h1>
<p>{{ object.creator.email }} has invited you for a Pokebattle. Choose your Pokemons below:</p>
<form id="battle-form" action="{% url 'battles:battle_update_opponent_pokemons' object.id %}" method="post">
    {% csrf_token %}
  <span class="field-error">{{ form.non_field_errors }}</span>
  <div class="field-wrapper">
    <label for="{{ form.opponent_pokemon_1.id_for_label }}">Pokemon 1:</label>
    {{ form.opponent_pokemon_1 }}
    <span class="field-error">{{ form.opponent_pokemon_1.errors }}</span>
  </div>
  <div class="field-wrapper">
    <label for="{{ form.opponent_pokemon_2.id_for_label }}">Pokemon 2:</label>
    {{ form.opponent_pokemon_2 }}
    <span class="field-error">{{ form.opponent_pokemon_2.errors }}</span>
  </div>
  <div class="field-wrapper">
    <label for="{{ form.opponent_pokemon_3.id_for_label }}">Pokemon 3:</label>
    {{ form.opponent_pokemon_3 }}
    <span class="field-error">{{ form.opponent_pokemon_3.errors }}</span>
  </div>
  <button type="submit">Battle!</button>
</form>
<a class="nav-link" href="{% url 'battles:battle_list' %}">Back to list</a>

<!--
django-autocomplete-light configurations to use autocompletes outside the admin
https://django-autocomplete-light.readthedocs.io/en/master/tutorial.html#using-autocompletes-outside-the-admin
-->
<script type="text/javascript" src="{% static 'admin/js/vendor/jquery/jquery.js' %}"></script>

{{ form.media }}
<script>
  (function($) {
      $('#add-form').click(function() {
          var index = $('#id_inline_test_models-TOTAL_FORMS').val()
          var newTable = $('#id_inline_test_models-__prefix__-DELETE').parents('table').clone()
          newTable.find(':input').each(function() {
              for (attr of ['name', 'id'])
                  $(this).attr(
                      attr,
                      $(this).attr(attr).replace('__prefix__', index)
                  )
          })
          newTable.insertBefore($(this))
          $('#id_inline_test_models-TOTAL_FORMS').val(
              parseInt($('#id_inline_test_models-TOTAL_FORMS').val()) + 1
          )
          newTable.slideDown()
      })
  })($)
  </script>

backend/battles/templates/battles/battle_settled_list.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'css/global.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/battle_styles.css' %}" />

<h1>Battles</h1>
<ul id="battles-list">
  {% for battle in object_list %}
  <li><a href="{% url 'battles:battle_detail' battle.id %}">Pokebattle {{ battle.id }}</a></li>
  {% empty %}
    <li>No battles yet.</li>
  {% endfor %}
</ul>
<a class="nav-link" href="{% url 'battles:battle_list' %}">Back too all battles</a>